#!/usr/bin/perl -w -CSDA
use strict;
use utf8;
use v5.010;
use Unicode::Collate;
use Storable;

my $uc = Unicode::Collate->new();

my %w_index;
my %dups;
my $offset = 0;

my $dict = shift @ARGV;

open (IN, '<', $dict . '.dsl');
while (<IN>) {
  next if /#/;
  unless (/^\t/){
    $offset = tell(IN);
    my $head = $_;
    chomp $head;
    $head =~ s/\x{feff}//;
    my $d_head = detone($head);
    unless (exists $w_index{$d_head}){
      $w_index{$d_head} = [$offset, $head];
    }else{
      if (exists($dups{$d_head})){
        $dups{$d_head}++;
        $w_index{$d_head . "-" ."$dups{$d_head}"} = [$offset, $head];
      }else{
        $dups{$d_head} = 1;
        $w_index{$d_head . "-1"} = [$offset, $head];
      }
    }
  }
}
store \%w_index, $dict . '.idx';
close IN;
say "$dict.dsl -> $dict.idx";

sub detone
{
  my $word = shift @_;
  $word =~ tr/ἀἁάάὰᾶἄἂἆἅἃἇᾳᾀᾄᾂᾆᾁᾅᾃᾇΑἈἉΆΆᾺἌἊἎἍἋἏ/α/;
  $word =~ tr/ἐἑέέὲἔἒἕἓΕἘἙΈΈῈἜἚ/ε/;
  $word =~ tr/ἠἡήήὴῆἤἢἦἥἣἧῃᾐᾔᾒᾖᾑᾕᾓᾗΗἨἩΉΉῊἬἪἮἭἫἯ/η/;
  $word =~ tr/ἰἱίίὶῖἴἲἶἵἳἷϊΙἸἹΊΊῚἼἺἾἽἻἿ/ι/;
  $word =~ tr/ὀὁόόὸὄὂὅὃΟὈὉΌΌῸὌὊὍὋ/ο/;
  $word =~ tr/ὐὑύύὺῦὔὒὖὕὓὗϋΥὙΎΎῪὝὛὟ/υ/;
  $word =~ tr/ὠὡώώὼῶὤὢὦὥὣὧῳᾠᾡᾤᾢᾦᾥᾣᾧΩὨὩΏΏῺὬὪὮὭὫὯ/ω/;
  $word =~ tr/ῥῤῬΡ/ρ/;
  $word =~ tr/ΒΓΔΖΘΚΛΜΝΞΠΡΣΤΦΧΨ/βγδζθκλμνξπρστφχψ/;
  $word =~ s/’//g;
  return $word;
}
